# Generated by Django 3.1.5 on 2021-01-08 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='headimg',
        ),
        migrations.AddField(
            model_name='customuser',
            name='headpic',
            field=models.ImageField(default='user/default.png', upload_to='user/', verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='邮箱'),
        ),
    ]
